/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

public class App {
    private static String[] classArgs;
    private static BufferedImage img;
    private static Bitmap readImage;


    public static void main(String[] args) {
        classArgs = args;
        verifyArgs();
    }

    private static void verifyArgs() {

        try {
            if(classArgs.length != 3) {
                throw new Exception("You must send in three arguments - input output transform.");
            }

            readFile(classArgs[0]);
            //methods we could use
//            readImage.makePink();
//            readImage.blackout();
            readImage.blur();
            writeFile(classArgs[1]);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private static void readFile(String filepath) {
        //read image
        try{
            File file = new File(filepath);
            System.out.println(file.getPath());
            img = ImageIO.read(file);
            readImage = new Bitmap(img);
        }catch(IOException e){
            System.out.println(e);
        }
    }

    private static void writeFile(String filepath) {
        try{
            File file = new File(filepath);
            ImageIO.write( readImage.getImage(), "bmp", file );
        }catch(IOException e){
            System.out.println(e);
        }
    }
}
